<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/private/bootstrap.php';
require_once dirname(__DIR__,2).'/private/timing.php';
$method=$_SERVER['REQUEST_METHOD']??'GET';$path=trim(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)??'','/');$parts=explode('/',$path);$api=array_search('api',$parts,true);$parts=$api===false?[]:array_slice($parts,$api+1);
if($method==='OPTIONS'){header('Access-Control-Allow-Origin: *');header('Access-Control-Allow-Methods: GET, POST, OPTIONS');header('Access-Control-Allow-Headers: content-type, x-cronochip-time, x-cronochip-signature');http_response_code(204);exit;}
function publicEvent(string $slug): ?array {$q=db()->prepare('SELECT id,name,slug,city,event_date,distance,category,status,appeal_minutes,appeal_ends_at,event_type,show_general FROM events WHERE slug=? AND is_published=1');$q->execute([$slug]);return $q->fetch()?:null;}
function resultCols(): string{return 'bib_number,athlete_name,gender,age_group,category,finish_time,finish_ms,finish_clock,status,distance,team,lap,overall_rank,gender_rank,age_group_rank,updated_at';}
function authDesktop(string $action,string $body): void {$time=$_SERVER['HTTP_X_CRONOCHIP_TIME']??'';$sig=$_SERVER['HTTP_X_CRONOCHIP_SIGNATURE']??'';if(!$sig||!ctype_digit($time)||abs((int)(microtime(true)*1000)-(int)$time)>300000)jsonResponse(['error'=>'Programa não autorizado.'],401);$key=file_get_contents(dirname(__DIR__,2).'/private/device-public.pem');$ok=$key&&openssl_verify($time.'.'.$action.'.'.$body,base64_decode($sig,true)?:'', $key,OPENSSL_ALGO_SHA256)===1;if(!$ok)jsonResponse(['error'=>'Programa não autorizado.'],401);}
try{
 if(($parts[0]??'')==='health'){db()->query('SELECT 1');jsonResponse(['ok'=>true,'service'=>'Cronochip Hostinger','time'=>isoNow()]);}
 if(($parts[0]??'')==='events'&&$method==='GET'){$rows=db()->query("SELECT id,name,slug,city,event_date,distance,status,event_type,show_general FROM events WHERE is_published=1 ORDER BY event_date DESC")->fetchAll();jsonResponse(['events'=>$rows]);}
 if(($parts[0]??'')==='event'&&$method==='GET'){$slug=trim($_GET['slug']??'');$e=publicEvent($slug);if(!$e)jsonResponse(['event'=>null],404);$q=db()->prepare('SELECT distance,gender,MAX(updated_at) updated_at FROM results WHERE event_id=? GROUP BY distance,gender');$q->execute([$e['id']]);$div=[];$last=null;foreach($q as $r){$d=trim($r['distance']??'');if($d!==''){$div[$d]??=[];if(in_array($r['gender'],['M','F'],true)&&!in_array($r['gender'],$div[$d],true))$div[$d][]=$r['gender'];}if(!$last||$r['updated_at']>$last)$last=$r['updated_at'];}$c=db()->prepare('SELECT COUNT(*) FROM results WHERE event_id=?');$c->execute([$e['id']]);jsonResponse(['event'=>$e,'total'=>(int)$c->fetchColumn(),'lastUpdate'=>$last,'distances'=>array_keys($div),'divisions'=>array_map(fn($d)=>['distance'=>$d,'genders'=>$div[$d]],array_keys($div))]);}
 if(($parts[0]??'')==='ranking'&&$method==='GET'){$e=publicEvent(trim($_GET['slug']??''));if(!$e)jsonResponse(['results'=>[]],404);$d=trim($_GET['d']??'');$g=$_GET['g']??'';$sql='SELECT '.resultCols().' FROM results WHERE event_id=? AND status=\'FINISHED\' AND overall_rank IS NOT NULL';$args=[$e['id']];if($d!==''){$sql.=' AND distance=?';$args[]=$d;}if(in_array($g,['M','F'],true)){$sql.=' AND gender=?';$args[]=$g;}$sql.=' ORDER BY overall_rank ASC LIMIT 50';$q=db()->prepare($sql);$q->execute($args);jsonResponse(['results'=>$q->fetchAll()]);}
 if(($parts[0]??'')==='search'&&$method==='GET'){$e=publicEvent(trim($_GET['slug']??''));if(!$e)jsonResponse(['results'=>[]],404);$term=substr(normalizeSearch(trim($_GET['q']??'')),0,80);if($term==='')jsonResponse(['results'=>[]]);$sql='SELECT '.resultCols().' FROM results WHERE event_id=? AND status=\'FINISHED\' AND (bib_number=? OR name_search LIKE ?) ORDER BY overall_rank IS NULL,overall_rank LIMIT 30';$q=db()->prepare($sql);$q->execute([$e['id'],$term,'%'.$term.'%']);jsonResponse(['results'=>$q->fetchAll()]);}
 if(($parts[0]??'')==='public'&&($parts[1]??'')==='ingest'&&$method==='POST'){$token=$parts[2]??'';if(strlen($token)<16)jsonResponse(['error'=>'Chave de envio inválida.'],401);$q=db()->prepare('SELECT event_id,paused FROM sync_configs WHERE ingest_token=?');$q->execute([$token]);$c=$q->fetch();if(!$c)jsonResponse(['error'=>'Chave de envio não reconhecida.'],401);if($c['paused'])jsonResponse(['skipped'=>true,'message'=>'Sincronização pausada.'],202);$body=bodyText();global $config;if(trim($body)==='')jsonResponse(['error'=>'Arquivo vazio.'],400);if(strlen($body)>($config['app']['max_txt_bytes']??20000000))jsonResponse(['error'=>'Arquivo muito grande.'],413);header('Access-Control-Allow-Origin: *');$sum=syncContent($c['event_id'],$body);jsonResponse($sum,$sum['ok']?200:500);}
 if(($parts[0]??'')==='public'&&($parts[1]??'')==='desktop'){$action=$parts[2]??'';$raw=$method==='POST'?bodyText():'';authDesktop($action,$raw);$pdo=db();if($method==='GET'&&$action==='events'){$sql='SELECT e.id,e.name,e.slug,e.city,e.event_date,e.event_type,e.show_general,e.is_published,e.status,e.appeal_minutes,e.appeal_ends_at,s.ingest_token,s.last_sync_at,s.last_error,s.connection_status FROM events e JOIN sync_configs s ON s.event_id=e.id ORDER BY e.event_date DESC';$events=[];foreach($pdo->query($sql) as $r){$events[]=['id'=>$r['id'],'name'=>$r['name'],'slug'=>$r['slug'],'city'=>$r['city'],'event_date'=>$r['event_date'],'event_type'=>$r['event_type'],'show_general'=>(bool)$r['show_general'],'is_published'=>(bool)$r['is_published'],'status'=>$r['status'],'appeal_minutes'=>(int)$r['appeal_minutes'],'appeal_ends_at'=>$r['appeal_ends_at'],'sync_configs'=>['ingest_token'=>$r['ingest_token'],'last_sync_at'=>$r['last_sync_at'],'last_error'=>$r['last_error'],'connection_status'=>$r['connection_status']]];}jsonResponse(['events'=>$events]);}$in=bodyJson($raw);
  if($action==='event'){$name=trim($in['name']??'');$type=$in['event_type']??'';if(strlen($name)<2||!in_array($type,['CORRIDA','CORRIDA_COM_VOLTAS','MTB','MTB_COM_VOLTAS'],true))throw new InvalidArgumentException('Dados inválidos.');$id=$in['eventId']??'';$city=substr(trim($in['city']??''),0,80)?:null;$date=$in['event_date']?:null;$show=!empty($in['show_general']);$published=!empty($in['is_published']);if($id){$q=$pdo->prepare('UPDATE events SET name=?,city=?,event_date=?,event_type=?,show_general=?,is_published=?,status=\'ACTIVE\' WHERE id=?');$q->execute([$name,$city,$date,$type,$show,$published,$id]);}else{$id=uuidv4();$slug=slugify($name).'-'.substr(bin2hex(random_bytes(3)),0,4);$code=strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',iconv('UTF-8','ASCII//TRANSLIT',$name)?:$name),0,8).substr(base_convert((string)time(),10,36),-5));$pdo->beginTransaction();$pdo->prepare('INSERT INTO events(id,code,name,slug,city,event_date,event_type,show_general,is_published) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$id,$code,$name,$slug,$city,$date,$type,$show,$published]);$pdo->prepare('INSERT INTO sync_configs(event_id,ingest_token) VALUES(?,?)')->execute([$id,bin2hex(random_bytes(16))]);$pdo->commit();}jsonResponse(['eventId'=>$id]);}
  if($action==='control'){$id=$in['eventId']??'';$act=$in['action']??'';if($act==='publish')$pdo->prepare('UPDATE events SET is_published=? WHERE id=?')->execute([!empty($in['value']),$id]);elseif($act==='appeal'){$m=max(1,min(1440,(int)($in['value']??15)));$pdo->prepare('UPDATE events SET appeal_minutes=?,appeal_ends_at=DATE_ADD(NOW(3),INTERVAL ? MINUTE) WHERE id=?')->execute([$m,$m,$id]);}elseif($act==='homologate')$pdo->prepare("UPDATE events SET appeal_ends_at='1970-01-01 00:00:01' WHERE id=?")->execute([$id]);else throw new InvalidArgumentException('Operação inválida.');jsonResponse(['ok'=>true]);}
  if($action==='delete'){$pdo->prepare('DELETE FROM events WHERE id=?')->execute([$in['eventId']??'']);jsonResponse(['ok'=>true]);}
  if($action==='screen'){$id=$in['eventId']??'';$term=trim($in['query']??'');$sql='SELECT bib_number,athlete_name,gender,age_group,category,finish_time,finish_clock,distance,overall_rank,updated_at,status FROM results WHERE event_id=? AND status=\'FINISHED\'';$args=[$id];if($term!==''){if(ctype_digit($term)){$sql.=' AND bib_number=?';$args[]=$term;}else{$sql.=' AND athlete_name LIKE ?';$args[]='%'.$term.'%';}}$sql.=' ORDER BY athlete_name LIMIT '.($term!==''?'30':'50');$q=$pdo->prepare($sql);$q->execute($args);jsonResponse(['results'=>$q->fetchAll(),'fetchedAt'=>isoNow()]);}
 }
 jsonResponse(['error'=>'Operação inválida.'],404);
}catch(InvalidArgumentException $e){jsonResponse(['error'=>$e->getMessage()],400);}catch(Throwable $e){error_log($e->getMessage());jsonResponse(['error'=>'Falha interna no serviço.'],500);}
